//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassageParlor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public DateTime Date { get; set; }
        public Nullable<int> ID_Worker { get; set; }
        public string Time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
