//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassageParlor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Worker
    {
        public int ID { get; set; }
        public Nullable<int> ID_Record { get; set; }
        public Nullable<int> ID_Worker { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
