//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassageParlor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheFirstNormalForm
    {
        public string Client { get; set; }
        public string Service { get; set; }
        public string Worker { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
